spring:

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mysql://mysql18:3306/test
    username: root
    password: root123


server:
  port: 9001

